<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hapus satu field</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>98864e32-d516-4efc-8159-9817a58dd7d4</testSuiteGuid>
   <testCaseLink>
      <guid>9d832445-5989-4988-ac0a-05b5f305ab9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 1/trade in - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80466a7-c2c4-4fda-ba7c-d44f109a96e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acef17bd-acbf-4cc0-803e-176927a7ee77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee444cbe-ba9a-4844-bfbe-407872aab0a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a5025ea-42fb-413a-8fc0-8d107dbdc731</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5376cb6-f727-448e-95eb-7ce1bc081af1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eb07416-0168-4e66-a818-9863b995eff2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efc7a6e8-216c-431c-a334-8da23a9140c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39f0b782-7c19-4d0c-a2fe-e6591808f30d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 1/trade in - page 1 - hapus lokasi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b63c71e-4d0f-4453-934e-404dce9b08f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2576c4ed-32cb-47f8-a3c9-d327f3a31bfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49243011-c95f-43be-8e4c-3bcd4f953751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e983a6b4-2eec-4a40-ae16-62b796409e15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35f90b3-0ce3-4a9e-97fb-e9b65628ec56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba5d3f76-e955-4b8d-943f-eefef2adb137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7c6b45a-7b3e-40a1-ba8f-c4770f6cd66a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5814d7c7-278f-409e-972f-07ed0c1688b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 1/trade in - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0213b41f-8c76-4dc1-95ee-3540c72149b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c761a5-a8f4-4bcc-a13b-86dfbf8f8ec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a213c881-76cd-41cd-8100-ba59434967d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2dffe75-5e47-42e6-abe6-78b578e0836f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd12674f-043f-4029-8dd1-88d7ea568eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e35ce6-ae17-43e9-af34-dd06c28acee3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>780face7-d5a1-4603-b8ff-19ab91d8fae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e93ee4bd-0652-4cc1-a88b-7388b9049fdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 1/trade in - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ab3570-576a-4da6-992e-ddfbeeaf4b67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e565741-42d1-4056-8adc-9832dbe3f3d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6b15167-929c-44d4-b171-300850bd1cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2c16667-156e-4c39-a768-70f7e804527c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46032156-2742-4ac5-9d63-d127489f06e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0927c39d-79c5-4c0f-b774-40c75d38a37f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d94af8-36d7-4421-9f68-2ec109971fca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66fcef93-9147-41f2-9dcd-42cee522a70b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 1/trade in - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>799e3e85-8a5b-4748-95e0-4b1796ca8e8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f61bd6a-6255-41ea-ac7a-a4fa3a77e371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85816b5-820c-4d2c-88a3-07deebf7706b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e96dbbf-e088-4565-891a-8ab5fe034da2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26d14e50-7aee-472f-be1e-d7b129070fa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97dc459a-d2f1-4ba8-8d59-7c68796676b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f78934eb-7fc2-4f3a-8df3-547cd24aab91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7094355e-cbbd-47db-98aa-f740f0c16f20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 2/trade in - page 2 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695f1e06-133a-4b3f-9fb4-0cfe62dd29ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47eee4b0-e7f5-4e07-9c79-03226d7dda1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d7b0f3a-69f4-45ff-8884-02abd2ff7692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64585268-e630-4adc-8a8d-7397d999b094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de07929f-b436-4644-a420-9d13aba29975</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c430c7-80ef-4dda-b6ab-6f0674b83f2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92453c27-28aa-4b54-ab9f-33acd89f47b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 2/trade in - page 2 - hapus lokasi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118e84ce-7004-4107-8072-c33d738a5c86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c9a621e-4800-4d71-a2b1-33133f15418b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6153d8f6-cc2e-49dc-89ef-b43798a8beac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>682f5f4a-3339-431a-9568-39f05d801be6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20065ab5-f059-4f3a-8db6-ed0a63ffac69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7767800e-349a-4cc4-b983-10ca7af2c1f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0fa7b00-b4b3-48cf-87bd-6d05c634b4c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 2/trade in - page 2 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee320f55-a5cc-4a0c-9d0d-cd12723567b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1a0a51-b661-4148-8475-23057b238576</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc82faa0-a4b2-42cf-a2e2-dda4cc0c1c4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>302c1540-f958-4844-be0c-1cefe7738839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f192bf62-67ba-4251-a892-94a0a34509ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2261bb2-0503-42d7-baba-7296db5103ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>444d3178-9dea-4e1b-889a-0c837142a91f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 2/trade in - page 2 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1ca0ac-689e-4843-af70-30f2ddac7465</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e436062c-ca26-4de9-a42e-10d33a1b2163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f62b02f0-9d2d-4538-8555-792ef76b7631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf7da6fa-3f8b-41f7-8e87-032895270795</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acf460b6-c85a-4fc9-8ee2-81896460d33b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47efd08-499d-4bfc-a676-072688054478</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b7b163a-33fe-445a-9d6d-ee55b09e6bb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 1 field/page 2/trade in - page 2 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>219d3c77-c888-4581-bffb-c1bbffb2729b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6d2c6b2-68e0-4674-b45d-1076c0169dad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>298e0971-7eb6-46f0-b8d1-b52a6aa90279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>697667ff-c80d-4b1b-9505-891a31ca43fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b53400d-c2ad-4a97-bf44-cfcaf4488b4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eddfe707-7f6b-42b0-b31f-e553f7cdfda5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
