<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hapus 2 karakter</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>fdb3044b-d501-40e4-a2ab-f4e1c8c43464</testSuiteGuid>
   <testCaseLink>
      <guid>3b19fbec-d308-405a-8950-cc72e3fb5ad1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 1/trade in - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>877c9172-30fc-4452-ab90-2f5050aa270c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8531edb-42a6-40aa-ab0f-26fc21413a0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cd6563b-b71a-4152-8864-8d14fc1b00b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eecfa43b-aacb-419f-adfb-34543961f530</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3fa6c9b-fbca-4451-9e93-80ab31d52549</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a81a7dab-4915-4b7a-85a7-39f99934622f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4c83c6c-fb17-487d-b14a-214af2643b35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>747caa2f-b261-4927-81d4-ee24dfb820bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 1/trade in - page 1 - hapus lokasi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb63ec4-8e76-455f-b8f2-026fdd6f97f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73127350-91bb-42d3-ab2b-3ddc5c9d81b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab0d9d6e-9c22-4ee8-8e46-a9c79437e9cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d33df414-4ea4-42ee-9cf7-83677bc7ae02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aa875b0-bd3a-4c6f-8a49-1fcdd264731a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fa41dd2-0cb1-4201-a20f-41d07f49d040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>183b0d4c-d7e7-48af-a97e-316eb38f9e41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4588b36-c210-4ba4-9e00-9c5eb2062dd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 1/trade in - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1124890-693e-400d-8262-8e0ef1848146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>000f9dd0-1ba3-49ac-b078-ddb0f811eac4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fab6793-2a09-4029-a38e-efb716b1fa95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>296a2cd3-62a8-46b8-aea6-eb0431007ab4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf977515-6eb8-4368-8924-7cc8d5eef566</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61926794-40c5-4fd1-ac5c-65e2d5988e13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ec9206b-8bb6-4af6-baa9-25cd2e3f1067</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>589a7238-101b-441e-be86-a0aa8cc017d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 1/trade in - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>712b4ee1-9a68-4c07-be61-8a376659f135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4b47226-d732-4528-800c-521d361a66b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65fa083c-9b35-4ca6-a194-5525996f1914</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9addccfa-6b27-41ae-8df1-c894cf526f1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8979ffc-30ff-4f72-b903-abc9abe663a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>807c1574-1786-44b9-81ca-c66106c8c193</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6afc910-de13-4175-9895-a77a18a2e939</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d351ced9-6867-45b4-87cf-98278fb0898e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 1/trade in - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5a7ad22-602e-4a3d-9c8d-7ebfcf4715d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4065f1fb-31af-4af9-9d20-0e341da2cede</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c73084f4-ad37-413f-9b81-6d25760f3b6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>463b31d6-2ae5-4d4e-b00b-79f9b0c147cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e7fae6-9de9-4521-a7cf-ce170a359c90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06a38f39-f813-4f34-a858-f405b0db623f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd02d250-e341-4a85-9bbb-561aff5651bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>387f4ef6-e157-45a6-b024-f80f582f5574</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 2/trade in - page 2 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ade959b8-5410-4993-a343-46be286d662c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d9f1ed-b9f3-4e6f-af61-be5f728e6135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bfcae2b-a4ce-4683-a700-a8ae3de07185</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17786d3d-69b4-4bba-acca-94eab5cc8bec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>948cd18d-d5b0-40eb-80ef-cfc5253a80e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfb8d2aa-350e-4fa7-8512-2a016dda838f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd7b1c75-771c-404f-80eb-9cb2e8d0d295</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 2/trade in - page 2 - hapus lokasi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>765a4a89-0590-4edc-90c6-23e81a7552d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4adeeab1-91fc-4881-b7b0-86141db22732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d06ba189-d6a9-4f2a-90b3-164c1e7c4090</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4ff518-ed88-4135-bdf6-b5393f359b78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>839b46f4-472f-484e-8f7e-8bc0ff34db99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad865d74-1788-45e3-95d0-7efae7011a7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85f37c45-83c4-4a98-b985-92f489d23735</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 2/trade in - page 2 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dabba5fb-3d72-40ad-b69d-64607f2882cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1895ab97-003c-4d72-9a56-f9c28401206f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fbe5058-c505-4fe7-b692-0a821cc9dd8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7728d722-8496-4edf-b610-3a39dd29cd1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2b4d6ee-134e-4254-8bb0-73ca28532a8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba631e82-2606-464a-a0ef-712ea960956b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6719688c-233e-4797-a6e1-6f6be08e2847</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 2/trade in - page 2 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e7d0946-25e0-4172-8323-b081a264cc33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad5f05d5-8935-4c4f-bf99-0934be5640a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f573ac1-3bf6-45ef-937a-4fe5f278403f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55af3376-dedd-42d4-97d1-ee7b4376a8ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4305b4cd-0cd4-4e9e-a19b-1e2b73f412a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13786559-d6e8-4386-a285-1a5941f73ca0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aab78f86-6f3a-4fa2-9564-f3ae084dda4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/trade in/flow hapus 2 karakter/page 2/trade in - page 2 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f47eeac-cee5-4731-a98a-20a9c6bc0feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1064ba-b64c-42a9-9b14-51f885b2dc53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afb6eaa8-2789-4a86-90f6-97de7785175d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6435811f-f4fb-47cd-8fe8-a6ba852fccc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78259e94-cb56-48ca-8a95-7f639bac7919</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>384ccba8-47cd-43ba-b222-4bd5384e7474</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
