<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hapus 2 karakter</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>86205bff-1eb9-4c58-aa9d-35142d389925</testSuiteGuid>
   <testCaseLink>
      <guid>211ed083-73ab-44d0-8a4f-2ce3f045e75f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17092f5d-9f04-4597-b6b7-75df8209a927</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dbde4a0-14d9-48b5-a1de-0ca01d91f875</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb924941-b5e6-4e8a-adda-1f56a215373d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1251cc3-3a60-4c1a-8f03-b7c9d471848f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0f1eceb-0625-4b99-b2c3-70135f487a5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3da862b-23d1-42d3-b000-c126066bc687</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ba33d3-0c90-4817-b434-a1b6060536b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a97282c-ca16-4b11-90d6-b36e854b6b40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4ccaa5c-2b47-446f-b9d5-11d1c44f561a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba3d5c17-8d44-4683-8604-05f6a34fb81b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de0a884a-0ffc-4478-ab95-466b06476057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b95a05f6-3c80-4b28-946a-90731187d456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e53cede-557d-4a71-97ac-883ef8f8f03c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf05208e-faeb-4e69-89b0-bfd5f24d740f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bfe389d-602d-4938-9de6-0de1a32b8768</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fbee0b1-064f-4433-a7bd-1d4f383b2d69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ca171fb-b730-4666-885f-23c63d943efc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>115bbe4c-7cc9-43e1-a573-8c4aa9b7f984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80023e3b-28a5-49e3-a3be-1e4d0d2ce2b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff04f944-32f2-4c39-ae95-5d7c45010dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus area pengajuan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46fab01-67cb-484b-bf17-2fbcc636da04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2cccc58-2a2e-4350-9131-0885ac4c655f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c3553f5-f880-4a68-b477-12757ac668b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcb86a18-bdb6-4440-a564-6aa828be0279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2beebdd1-cc59-4678-aada-e14daddf3d44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a98239b-6aaa-45ed-81ad-b7eeb86ffc71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c444ceb-568a-4d0b-a267-a75d79ac6c37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus cabang acc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77debd97-0fd4-46e3-87ed-fd834666db37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30e12207-8b51-47d0-b676-325f8354fee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e7f0f0f-288a-46b0-8165-d3e282c216dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef7ad49-b953-417c-a95d-69040d02421d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6831645-7e7f-48a8-91a0-61e2e42e2ecd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aa215f8-824c-409b-b815-2d09458f42ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c1b91bc-3683-4c5c-9179-51d0cdd8a49a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus dana yang dibutuhkan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c56761d-737f-4b34-9959-ed8410e96ef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5259e531-0352-4867-8c17-530a5a5770e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ae82a39-07ab-4ebd-927c-1d22eaa66015</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf74dbf8-1e0a-4fa1-a754-24ad59a76a76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a92d3f53-f8a0-4e23-933d-86db9cd82361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6caaed97-1d2d-4730-b1d4-c9cc3c2ab272</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04d1d625-7b37-41f5-abe4-42ab5a99d972</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus tujuan peminjaman dana</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe616220-6516-4a5f-a6ea-26d379b84826</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63cf3079-8b6f-458b-8b9e-c6890fc1e189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb01c542-f6f2-4a20-ba2f-4a17ee04a764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb63502b-33e4-4773-a9f5-3e7567df13bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>012c1165-5f33-4320-bc66-07b73078944b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>352849d4-bfd4-4062-9ce0-081d843215b1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
