<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hapus satu field</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f3873499-141c-4339-9a4b-00552528af75</testSuiteGuid>
   <testCaseLink>
      <guid>1ff721f3-90ac-4a0c-9a1c-f7fa629c5211</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27bbcd3a-b22e-4e18-bf44-1a48c8d44674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d89460f-e6db-4779-95ae-2e3c9fa26cbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4061e1cb-3a6c-41f4-8774-b473804f52dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24fa82a6-095f-44ef-aa92-34ae62bbc78a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bd8a77e-bd6d-4811-ac9f-c28020f45cdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dcaf9ba-ff28-4430-bb41-a8d900571905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>781762d4-0c10-4c09-8f74-a1fc7039bfc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>577ae290-0357-4e23-9e88-f8557a8900f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2fe43f8-68f8-4eef-8136-5bc81107559e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0a620f0-1f5e-4041-8e0d-953c60925977</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cafc674-b895-424c-88c3-89a215e03e5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f00d535b-451c-401d-83a2-84b8493add8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170cd737-6d3e-4256-b5be-ee70c59736ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b13b7-c87a-4932-bd37-90856b925854</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ee62e2d-a0ac-47c3-9af9-2b74fd7c369d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8afb9dc-aa62-418c-8ec0-98f17acd7d66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63aeddb9-cada-4117-8f55-092691c2cd88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3d4768-e625-45cb-841d-0803ef1f34da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e09487e-6125-49fb-b1cd-fa1c449a2c6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4736c0e-65b8-45eb-9fb5-75a66dcfadd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus area pengajuan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2484077-7970-44c6-899f-68e81632bc9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75047e21-a7bb-4070-9137-3a56b5770515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b068b5b-b296-44c2-9216-11785f7474c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ced1e14c-1ad0-46a3-92fe-9d6e312b14a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d782d00-117c-4a4c-bcde-196a051373f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11414097-0225-42f3-b171-3b98e08c831c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3822f5a2-5438-4cb4-b555-64401f106ecf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus cabang acc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>714758a3-ea05-4b92-b0e8-d32dc46af25f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc544e21-d71f-4439-8b24-d38d56dd2938</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2aa580b-addf-4be3-92cf-69cb82d9f10e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0a6e478-de36-4c8c-b793-57444299b5e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe093119-1f4c-4cef-b691-c50b8c6b6812</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ac5e74-b683-4aaf-8bfe-47a1c684f0aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3c96e1b-159b-462f-b177-aa87b8250aa2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus dana yang dibutuhkan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941d7a16-fda0-44cd-bfaa-b1a5e7f26fb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a3d5f6-861b-414a-852b-f0b798724d9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d77efd8e-c234-4fab-bfa3-072a5532c0a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4805bb43-30a5-486f-9a7e-75a7e93b8785</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c6b77d0-98ec-434d-a0f9-0a46210db150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d0535ee-ea07-4e32-aff8-26c07055d203</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d6a8e0e-6b5c-4b19-a6a4-0a48e08ccde7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus tujuan peminjaman dana</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72cd6414-6bbc-49d1-85e7-072d5038c5dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4cc056f-c2cd-41be-8240-4390d3b57961</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3690f420-2cb6-4f61-8f4e-fe62a750a28c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a3cb26-8e84-49ef-8899-83c2c0374642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebe46ce5-dfae-48c4-94d0-b903970c0664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7015abdd-369b-465d-8755-ab65f3f4cf5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
