<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MOBILE_TS_Multiguna - validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f9d4775f-5cdb-4843-b4f7-ca357309ecd5</testSuiteGuid>
   <testCaseLink>
      <guid>dc3072eb-249f-4804-bcac-949de44d777e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/validation/Multiguna - Belum Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4c09f3d-d638-4ab6-ad54-de4fcd3e7915</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b66778dd-3310-4c67-bd0e-c0fcfc46244c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b94bcbd-a1a7-4f1b-8f9f-81f6f433b828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed5bdbcb-a1cc-4274-b279-bc273cf0ed6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a409326d-913b-49e4-a835-74df5e69e5d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1c8668-95fe-4789-bf52-d479822134d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60692865-76cf-4991-8a3b-1ca03bf2233c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/validation/Multiguna - Belum Upload KTP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ea5f69-dc47-4b0b-bdd3-c5dd74570cec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8af0fa98-80e4-4d5c-bbc2-b61058c8e1df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbc8e39-743d-47d8-9867-21f6f7c66061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34269355-d913-49db-9a15-6a124866fd31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69836da8-fab4-4516-8d79-2e9b99b08a4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ac024ab-8f98-492d-9c31-711b66aa5850</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fbdfd72-f170-408b-9f36-48d3ba69669d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/validation/Multiguna - page 1 - cek field input output</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da99579a-ada2-4b4c-8032-165b9078a85b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48d5aaf0-4a7e-477e-8d27-7546afd86178</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba555a2a-5e91-4ada-8783-8b3ca84ca307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bbfcf51-3b83-46ca-ba00-b3ad3e20826c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8796cf14-352f-4c02-a863-a829fa3fef03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57303d8e-8156-4f6a-b4c6-aae335d06443</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c61177d7-9a8a-4e93-9d93-992eb96c2737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1272a24-8a77-4905-ad77-dd536dcb2e01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/validation/Multiguna - slider menu - belum login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04919c1d-c8cd-447f-aaa0-f595a860e484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cda15aa-db7b-427b-b098-4e5d883e30f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b997a3b4-5633-4cb3-85a8-bf66607a452f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0035fb41-672f-46ff-becd-6d79f3515309</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c6d5257-53d7-4862-a04f-5a3aee6fa538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1feeac00-8cf8-42bb-a16c-b1fc6f8c6ab1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
