<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MOBILE_TS_Multiguna - flow hapus 1 field</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>323189f5-a0ac-4103-9240-261373f7025e</testSuiteGuid>
   <testCaseLink>
      <guid>60057c5c-620b-4703-abbe-2d18051616cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>645dd52f-13c0-4c3d-bb8e-d03b0ccfea36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe711cfa-9279-4d12-9b0d-1647acdf9945</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05aad19-7478-4a45-b59f-58046d0e80bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2107f0f-64f8-441a-901c-87180b77ec71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aa7546f-a7e2-43dd-ae51-1913fcba34c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcee1586-6d90-4d10-8b82-e231721ffa76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7a4df3e-e5c1-40de-8842-56aec391af66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b57270f-b294-443e-8e9e-c88a41699ad0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f97da53d-184f-4a73-bcf7-7e11eac85f15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16aab9ed-ef98-488d-adff-569bd6b9e942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09488b9e-d172-4db0-b1ec-1adeb2f54237</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd814e94-89b4-4b28-bfd5-72b044e5f060</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3069a808-fff4-4173-a090-0e7df76cb4cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fd2cef0-69eb-4535-98ec-a4c2cab4a007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7a57d4e-05da-48c2-bd5b-25f47b380ac5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8c7dc6f-ab2b-4c78-97d4-ec7d1f820c24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccc666d8-4f95-497c-af86-a91a98addd8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c882b9e3-ecfe-4757-90a9-0e6178249624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecff1c83-6ab4-4605-aca8-546025ff377a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1905216c-1796-431c-ab15-e3008f3cd313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08c935b6-5b2b-4715-9065-e7be6ad6a93c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efcdc128-e213-4509-8277-cc4c27e42687</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78df9a5a-3fb5-46ca-907b-6306e4d02f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d3fc287-0a84-4b73-a473-54c72d49ed4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 1/Multiguna - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43033511-2d9a-458c-9fa5-6d5e351d0fdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71422645-d886-45a9-b180-9ba9e9da60df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2451c24-9d57-4180-b92e-d70afb8841ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6bd245e-d2f4-4ef9-8ca7-806ad9869231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5d8413f-6497-48d1-868e-515e445092b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b426ca-b4d7-448e-806d-16feaf9933f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63897b31-4626-4b4d-a69b-aa1e3a5b91d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a2e7b69-3205-4f4d-843d-bacb96a573fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus area pengajuan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bf130b6-234c-4f12-921d-84b2c0215625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfdf2e5c-b838-4beb-a034-25520d3ca986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da61498-1dd2-4c60-91ba-0c696c98d7bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a064fc7-9785-446d-8e6f-1854cbb9722b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fb81c7b-88e4-486b-b48b-05551114d415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db64dc22-5179-47cf-9eb1-77d1935fd76e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37aea9e3-8405-40c1-821b-6fcc131b9b90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus cabang acc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a847bb-26a3-43b0-8b91-da0a67480120</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1abdcdc8-546c-4874-a427-346e9f33530a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1019a1f5-cca1-4397-9070-d204b9661db9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e89d20-b951-41c4-94bc-c408053376c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b6f2d8-3fa8-4ab3-8d16-8c66290f793f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7548f9ef-52cf-47ea-af50-898f2b57f71a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5474a3e3-0d8d-44a0-9fa7-98546445c155</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus dana yang dibutuhkan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a9bea7c-2127-4aef-99da-90855893b041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fffffc5b-b511-4555-bb60-870526c7b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff03c590-fa0d-45ee-9167-1ff90113a8c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0d54024-8592-48d0-862d-06083ca4367e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dc3398d-6c34-431e-9012-4c3956b41463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4611ea47-3517-4beb-96dc-278705cb0f20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86eb8dd2-3b6d-43be-96a0-177a122709e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 1 field/page 2/Multiguna - page 2 - hapus tujuan peminjaman dana</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd942f1b-8366-4780-8c81-144904fde41f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aca3f335-c83f-4451-95e5-608de19bfe5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90c2113a-1723-496c-956d-b335f5ca58c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d05fa13-845c-4d19-b185-c7691317419d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4575164f-fa1c-41c6-93c8-52d8bccee2ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c7d698b-efb2-450c-816f-c7ec8f808926</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
