<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MOBILE_TS_Multiguna - flow hapus 2 karakter - page 2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2165155d-33e7-444e-b701-9fb8bf2d8d22</testSuiteGuid>
   <testCaseLink>
      <guid>d8b16ad3-f67d-492e-8fe7-af581dd965e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus brand</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1db8da2e-d78e-4abd-8b3c-3c8b1acbdbb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9e17c4f-bf9c-4741-8158-1e4f5896e317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b41c93-73f2-4701-b311-1e685098ac39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20c3266-ce75-4af3-ac9f-b8703e92a94e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9c9fecd-5786-4aba-9cbf-92fb9ae6cb78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc093648-b7af-4b8c-a800-7aef8aabcab1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb5001f-d537-4d9b-9e88-c7dae989dc0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b13407f7-2e8a-4c84-b199-e00d67951a4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus model</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c612bc-3993-472d-ab9b-ece5ac73bc31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c85f62b7-3469-485e-b376-f7fb40b27259</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5229a446-39db-4af2-8fda-532e52809e17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84feddfe-4f83-43a8-a96c-51a8ec106889</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5454143a-2ca3-44b6-bffb-0df6ff635ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b15e841-bf2d-40c8-aa78-fa1fcc8a5980</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f02cf347-12a3-4be9-8d03-271f34cb4712</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9bc7b84-9a9a-4b8b-8c5f-0a07b5cd7a92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus tahun</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2c2cf4e-b6e0-4e01-880b-5d00b21738ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bff6464-f2db-44f0-8e00-c6338d187335</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dacc48b3-4157-4735-a1be-472fa0b43ccd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eef105b5-86fe-4acd-b87a-7bafd5a658aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f81364-9e92-49c7-b262-a8dae10e9155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3993782d-4377-4fdd-bee4-0e51bbfb6c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc8003c-9fc5-4df8-893a-383c58551895</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aad8176a-a2a8-48e7-9e68-5a8e5f14ba79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 1/Multiguna - page 1 - hapus type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c723ed2-6fc0-45c1-9426-d08024a78eec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b010b574-044c-44c8-af26-cf4b59163c6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eb8b00a-f86c-4e6d-b8d6-f607819d6007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a9e6676-fb2a-402f-b3fc-66ac0b00af25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4deaaa48-eef8-4549-8c19-e1d10c3d20a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>865652d9-df2e-47da-b3e6-61f41b1ece3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e4d127-db86-4da1-a30e-416a2e9112b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da92a61f-44d3-40a5-9c6f-d0eea448724f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus area pengajuan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ce4fd7a-04e6-4d93-ad61-d2acb80b03ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a216ab2b-761d-45b6-985a-b1b509e808b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c00ccf-2874-45de-b520-c6c0ef0824f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ddfec13-bc15-4db2-8067-c46f13265f54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6e91234-9fb0-471e-aaa2-cc1c5c565646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14a29565-40d2-4aca-af09-ab10897fafa3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce6986c0-1f67-4e0d-8a39-c3987f3dd656</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus cabang acc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3095242-6ee5-478e-828f-8080b6eab306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6904d81-3a47-4d1b-8a90-e399c63f5b39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5e8b153-cfa7-413b-a52d-4a990613400c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33f95420-67bb-4f4f-bdbe-c06133651bd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe801ebc-67e3-4cfb-ad29-1294ab3438c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd057f8-dd23-4d71-9411-fef335277814</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9986fd26-c55f-4619-b956-e3b45952a22f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus dana yang dibutuhkan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1b7aa4d-c759-4863-9d4b-da824884bb02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c887de4a-a768-4b94-84e6-6f69fbb0bf1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd350068-7033-4709-842a-f4887eeafc8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8655067-3700-4348-8538-e3a1a524cb82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8be52964-cc96-438d-88d6-db394fd2211a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3cee94-f663-4269-bc28-a52037c80af9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c229221-a506-4cb7-a9c5-ce543e0cda9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow hapus 2 karakter/page 2/Multiguna - page 2 - hapus tujuan peminjaman dana</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>376111f1-e65a-49de-92b7-220b53260522</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>998a05fd-2f1d-4262-ab65-bd5a22140728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d87381e-5ca6-4162-ab52-6816bc370723</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9836b480-3aa3-496a-a332-e4e19be987e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86489e87-cc51-4393-8ad7-309c8903b801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d71284e0-70ff-4444-82ea-f4ef9ddd3c0c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
