<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MOBILE_TS_Multiguna - flow back page</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b3243e08-3d3f-4705-84dd-fed28ff33c89</testSuiteGuid>
   <testCaseLink>
      <guid>81dc1ab3-68e0-4245-bdeb-9f6f016b4be9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow back page/Multiguna - flow back 2 - 1 - 2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b1d9c00-fc16-4120-8fe3-9bc980e4f7ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44ed6ed0-50da-4330-bdf8-c605c5dc9580</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad3bab18-ddf3-45d4-b75e-403c93f727d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab77ba09-6f4f-4fc7-baa0-8573e75d45c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd65e2a5-0c7d-44b4-b567-bbff728b0dcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83ee3dff-2ffd-4ee0-8a7e-919d84ea1823</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44de05bb-0601-4eb2-a367-c971e5d3dc4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow back page/Multiguna - flow back 3-2-1-2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>778a04cf-9f3a-4a40-bc1a-6c9e1945e745</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5128410f-2328-48a2-a38d-848cff712ebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>932d2fe5-c757-4de2-8f02-d94f4542feea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0e88b4-eced-4ca5-a4af-75e59bff0156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d34437-b71b-4b8a-a1f4-1de75292ffc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68329393-f479-4d26-8032-39dfdf9c05a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec00b23-9fcc-47db-bd60-09ca9956a330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47edb627-4e08-4b0b-8f8a-775edfc0374c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b260cb55-5913-4812-a3f7-b222602291b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7325f1d-a42a-4754-8dec-945081c85647</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard/Cari Dana/multiguna/flow back page/Multiguna - flow back 3-2-3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99d4c54-77b7-4b81-8955-a91573b32dc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d7e7e4b-5df8-4ddb-9043-ed7f14901485</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5490539-9259-4f35-b457-e89990439b5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec92ac9c-f277-4e1f-a8fd-2b6f1ceea6ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16cc1217-c8cc-4756-8330-1d0fd8252b7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c0be2f-1c8d-481d-980d-274b6894be14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>632e9867-3bbd-4261-8017-418d7dcc4ce6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13661a20-85a0-4019-beab-1782be612bb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60db0820-0b10-4435-af3d-b4e5406c6dd4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
